version: '3.2'
services:
  report_bot:
    build:
      context: report_bot
    stop_signal: SIGKILL
    ports:
      - 8080:8080
    networks:
      - webnet
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - webnet

networks:
  webnet:
